name: GitHub Actions Demo
run-name: testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Add data to DB
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://opensourceapi.vercel.app/api/health'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"message": "Drink lots of water - Pradumna"}'
